login:
  path: /login/{email}
  methods: ['POST']
  controller: ImHere\Routes\V1\Login::login
profile:
  path: /profile
  methods: ['GET']
  controller: ImHere\Routes\V1\Profile::getProfile
status:
  path: /status
  methods: ['GET']
  controller: ImHere\Routes\V1\Badger::status
checkin:
  path: /checkin
  methods: ['POST']
  controller: ImHere\Routes\V1\Badger::checkin
checkout:
  path: /checkout
  methods: ['POST']
  controller: ImHere\Routes\V1\Badger::checkout
who:
  path: /who
  methods: ['GET']
  controller: ImHere\Routes\V1\Watcher::whoIsOnline
reportPerMonth:
  path: /report/monthly/{yearmonth}
  methods: ['GET']
  controller: ImHere\Routes\V1\Watcher::reportMonthly
  defaults: { yearmonth: none }
